### ISSUE TITLE
problem with get_O3_burden

### ISSUE THREAD

**Issue by BenNewsome** [tsherwen/AC_tools#47]
funcs4GEOSC.get_O3_burden expects a 4d array returning from get_GC_output.

In the test suit it is failing because the test netCDF file is only 1 month and so has no time dimension.

Is this a problem with get_GC_output or get_O3_burden.

Should ctm data with 1 time unit have a null dimension inserted, or should get_GC_output be able to take 3 dimension data?

**Comment by tsherwen** [comment]
Added a gotcha to extend dimensions by 1.
