### ISSUE TITLE
py.test now fails for AC_tools on "test_get_HEMCO_output_for_WD"

### ISSUE THREAD

**Issue by tsherwen** [tsherwen/AC_tools#63]
py.test now fails for AC_tools on "test_get_HEMCO_output_for_WD". I think the data is no included in the download list?

"
ts551@earth:Tests$ py.test
Downloading file. This might take some time.
Download complete.
Downloading file. This might take some time.
Download complete.
Downloading file. This might take some time.
Download complete.
Downloading file. This might take some time.
Download complete.
==================================================== test session starts ====================================================
platform linux2 -- Python 2.7.12 -- py-1.4.27 -- pytest-2.7.1
rootdir: /work/home/ts551/labbook/Python_progs/AC_tools, inifile: 
collected 34 items 

test_bpch2netCDF.py s.
test_funcs4GEOSC.py .s....F.
test_funcs4core.py .........
test_funcs4generic.py .
test_funcs4pf.py .
test_funcs4plotting.py .ssssssss
test_funcs4time.py ..
test_funcs4vars.py ..

========================================================= FAILURES ==========================================================
_______________________________________________ test_get_HEMCO_output_for_WD ________________________________________________

    def test_get_HEMCO_output_for_WD():
>       arr = get_HEMCO_output(wd=wd, vars='ALD2_TOTAL')

test_funcs4GEOSC.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../funcs4GEOSC.py:740: in get_HEMCO_output
    HEMCO_data = Dataset(fname, 'r')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   IOError: No such file or directory

netCDF4/_netCDF4.pyx:1811: IOError
====================================== 1 failed, 23 passed, 10 skipped in 5.59 seconds ======================================
"

**Comment by BenNewsome** [comment]
Should be fixed with latest push. I deleted all my data and re ran the tests and they all passed. Let me know if this fails for you.

I had the script trying to convert all the hemco files to a single hemco file in the dir with ctm.nc, but i had no error checks to make sure that a hemco file actually existed. Checks are now implemented and warnings given.

**Comment by tsherwen** [comment]
Checked. It is working nicely. Thanks @BenNewsome
