### ISSUE TITLE
Colourbar now failing with nans from updated method.

### ISSUE THREAD

**Issue by BenNewsome** [tsherwen/AC_tools#64]
problem created in funcs4plotting.get_human_readable_gradiations

**Comment by tsherwen** [comment]
What is the error message? The previous implementation may not have been the most elegant, but I believe it worked acceptably? If we revert I could take a look at making it more readable.

**Comment by BenNewsome** [comment]
I was passing NaN as my vmin and NaN as my vmax. I don't think it was due to my update now, more I was trying to create a colorbar that went from NaN to NaN... The old method is still in the code if you find it is not working so can still change it back if it changes anything, but I don't think the method is the same...
