### ISSUE TITLE
Create a nice encompasing species class

### ISSUE THREAD

**Issue by BenNewsome** [tsherwen/AC_tools#80]
Example
PAN = Species('PAN')
PAN.rmm = 20
PAN.name = CNMEPSLE (Chemistry...)
PAN.LaTeX = CA$_2$OMNS
PAN.InChI
PAN.carbons = get_carbons(self.InChI)

The CSV format from MChem tools works ok enough to adapt.

**Comment by BenNewsome** [comment]
Have a property string allowing the ability to do the following:

print(PAN)
$ PAN
print(PAN.string)
$PAN
print(PAN.name)
$ACTUAL_PAN_NAME_HERE...

**Comment by tsherwen** [comment]
Update to use the table from the GEOS-Chem species page on the wiki. 

http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem
